// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDg2y4WS9aQcBACLpgn1IECBzuERNGnUmU',
    appId: '1:717904034327:web:2a7a247f17cec499007a52',
    messagingSenderId: '717904034327',
    projectId: 'strivespark-86c76',
    authDomain: 'strivespark-86c76.firebaseapp.com',
    storageBucket: 'strivespark-86c76.firebasestorage.app',
    measurementId: 'G-RKC4TZSGEV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFtODOACYF2ZyPoSz3AseTlHrv1Ej86N8',
    appId: '1:717904034327:android:977b1c465ee060c6007a52',
    messagingSenderId: '717904034327',
    projectId: 'strivespark-86c76',
    storageBucket: 'strivespark-86c76.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWeu8umWvbLa3hV7JLynQPYkDdz8MPuA4',
    appId: '1:717904034327:ios:31e1bfb88d5ba5d1007a52',
    messagingSenderId: '717904034327',
    projectId: 'strivespark-86c76',
    storageBucket: 'strivespark-86c76.firebasestorage.app',
    iosBundleId: 'com.example.strivespark',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWeu8umWvbLa3hV7JLynQPYkDdz8MPuA4',
    appId: '1:717904034327:ios:31e1bfb88d5ba5d1007a52',
    messagingSenderId: '717904034327',
    projectId: 'strivespark-86c76',
    storageBucket: 'strivespark-86c76.firebasestorage.app',
    iosBundleId: 'com.example.strivespark',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDg2y4WS9aQcBACLpgn1IECBzuERNGnUmU',
    appId: '1:717904034327:web:0f749ca205051714007a52',
    messagingSenderId: '717904034327',
    projectId: 'strivespark-86c76',
    authDomain: 'strivespark-86c76.firebaseapp.com',
    storageBucket: 'strivespark-86c76.firebasestorage.app',
    measurementId: 'G-JZGM7XW2JP',
  );
}
